### ISSUE TITLE
Stable release missing on Packagist

### ISSUE THREAD

**Issue by Hazzeldorn** [breadbutter/breadbutter-php#1]
Hi guys

Composer throws an **InvalidArgumentException** when installing your package because there is no stable release yet.

Would it be possible for you to add a stable release with version number? Otherwise the content of the package could be different each time you reinstall it if you make changes to it.

Cheers,
Hazzeldorn

**Comment by ango-breadbutter** [comment]
Thank you, this has been fixed with the latest commit!
